version: '3'
services:
   web:
     depends_on:
        - database
     build:
        context: ./app
        dockerfile: Dockerfile
     restart: always
     image: vertenti/petshop-pipeline
     container_name: 'app-pipeline'
     ports:
        - "8003:80" #Porta mapeada no proxy reverso
        - "4444:443"
     volumes:
        - /var/www/docker/vertenti-pipiline/app:/var/www/html/petshop.com.br
        - /var/www/docker/vertenti-pipiline/apache/logs:/var/log/apache2
     environment:
        - APPLICATION_ENV=development
     links:
        - database
        - ruby

   database:
     depends_on:
        - ruby  
     image: mysql:5.7
     restart: always
     container_name: 'mysql-pipeline'
     command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
     volumes:
        - /var/www/docker/vertenti-pipiline/db/conf.d:/etc/mysql/conf.d
        - /var/www/docker/vertenti-pipiline/db/mysql.conf.d:/etc/mysql/mysql.conf.d
        - /var/www/docker/vertenti-pipiline/db/data:/var/lib/mysql
        - /var/www/docker/vertenti-pipiline/db/log:/var/log/
     environment:
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_DATABASE: petshop
     links:
        - ruby
         
   ruby:
     build:
        context: ./cucumber
        dockerfile: Dockerfile
 #    restart: always
     image: vertenti/cucumber-pipeline
     container_name: 'cucumber-pipeline'
#     privileged: true
#     command: Xvfb :20 -screen 0 1366x768x16
#     command: tail -f /dev/null
     shm_size: 512M
     #environment:
     #   - DISPLAY=:99
     #   - APPLICATION_ENV=development
     volumes:
        - /var/www/docker/vertenti-pipiline/cucumber/petshop:/usr/src/app/cucumber-petshop
#     tty: true
